language: go
go:
    - 1.5
addons:
    postgresql: "9.4"
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mig"
    email:
        recipients:
            - ulfr@mozilla.com
        on_success: never
        on_failure: always
script:
    - make all AGTCONF=conf/mig-agent-conf.go.inc
    - yes | bash tools/standalone_install.sh
