language: go
go:
    - 1.5
addons:
    postgresql: "9.4"
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mig"
    email:
        recipients:
            - ulfr@mozilla.com
        on_success: never
        on_failure: always
before_install:
    # this is a fix to get rng-tools to work in travis-ci
    - sudo apt-get update -qq
    - sudo apt-get install --yes rng-tools
    - sudo rm -f /dev/random
    - sudo mknod -m 0666 /dev/random c 1 9
    - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
    - sudo /etc/init.d/rng-tools restart
script:
    - export OLDPATH=$(pwd)
    - cd
    - mkdir -p "$GOPATH/src/mig.ninja/"
    - mv "$OLDPATH" "$GOPATH/src/mig.ninja/"
    - cd "$GOPATH/src/mig.ninja/mig"
    - diff mig-agent/configuration.go conf/mig-agent-conf.go.inc
    - diff mig-agent/available_modules.go conf/available_modules.go
    - diff mig-loader/configuration.go conf/mig-loader-conf.go.inc
    - diff client/mig-console/available_modules.go conf/available_modules.go
    - diff client/mig/available_modules.go conf/available_modules.go
    - make
    - yes | bash tools/standalone_install.sh
    - ./bin/linux/amd64/mig-agent-latest -i actions/example_v2.json
    - ./bin/linux/amd64/mig scribe -t status='online' -z -path actions/scribe/usn-2015.json -onlytrue -human
